# Site settings
title: Tinger Blog
SEOTitle: 小裙子的博客 | Tinger Blog
header-img: img/home-bg.jpg
email: 84454663@qq.com
description: "生活 前端开发 CSS JavaScript  百度前端技术学院 框架"
keyword: ""
url: "http://www.littleltt.com"              # your host, for absolute URL
baseurl: "/LvOlivia.github.io"         # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: false
weibo_username:     是你的小裙子呀
zhihu_username:     LvOlivia
github_username:    LvOlivia
#twitter_username:  LvOlivia
facebook_username:  LvOlivia



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important


# Disqus settings
#disqus_username: _your_disqus_short_name_

# Duoshuo settings
#duoshuo_username: _your_duoshuo_short_name_
# Share component is depend on Comment so we can NOT use share only.
#duoshuo_share: false                    # set to false if you want to use Comment without Sharing




# Analytics settings
# Baidu Analytics
ba_track_id: 4cc1f2d8f3067386cc5cdb626a202900
# Google Analytics
ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
ga_domain: littleltt.com



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "如果你越来越冷漠，你以为你成长了，但其实没有。长大应该是变温柔，对全世界都温柔♡"
sidebar-avatar: /img/avatar-hux.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Friends
friends: [
    {
        title: "Tinger Blog",
        href: "http://www.littleltt.com"
    },{
        title: "张晓晓",
        href: "http://www.xiaopandas.com"
    },{
        title: "鱼鳍",
	href: "http://www.fish7.top"
    }
]
